basePath: /v1
definitions:
  helper.BaseResponse:
    properties:
      data: {}
      error: {}
      messages:
        type: string
      meta:
        $ref: '#/definitions/helper.Meta'
    type: object
  helper.Meta:
    properties:
      page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
  model.TopupWalletCustomerRequest:
    properties:
      amount:
        type: integer
      payment_channel_id:
        type: integer
    type: object
host: localhost:8081
info:
  contact:
    email: taufikjanuar35@gmail.com
    name: Taufik Januar
  description: LezPay API - Customer Services
  license:
    name: MIT
  title: LezPay API
  version: "1.0"
paths:
  /dashboard:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Get Customer Dashboard
      tags:
      - Customer
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Checking Health Services
      tags:
      - Health Check
  /topup:
    post:
      consumes:
      - application/json
      parameters:
      - description: topup wallet customer
        in: body
        name: topup
        required: true
        schema:
          $ref: '#/definitions/model.TopupWalletCustomerRequest'
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Topup Wallet Customer
      tags:
      - Topup
schemes:
- http
swagger: "2.0"
