// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/v1/merchant/merchant.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantServiceClient interface {
	CreateMerchant(ctx context.Context, in *MerchantRequest, opts ...grpc.CallOption) (*MerchantResponse, error)
	UpdateVerifiedMerchant(ctx context.Context, in *UpdateVerifiedMerchantRequest, opts ...grpc.CallOption) (*UpdateVerifiedMerchantResponse, error)
	GetMerchantDetailsByEmail(ctx context.Context, in *GetMerchantDetailsByEmailRequest, opts ...grpc.CallOption) (*GetMerchantDetailsByEmailResponse, error)
}

type merchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantServiceClient(cc grpc.ClientConnInterface) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) CreateMerchant(ctx context.Context, in *MerchantRequest, opts ...grpc.CallOption) (*MerchantResponse, error) {
	out := new(MerchantResponse)
	err := c.cc.Invoke(ctx, "/proto.v1.merchant.MerchantService/CreateMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) UpdateVerifiedMerchant(ctx context.Context, in *UpdateVerifiedMerchantRequest, opts ...grpc.CallOption) (*UpdateVerifiedMerchantResponse, error) {
	out := new(UpdateVerifiedMerchantResponse)
	err := c.cc.Invoke(ctx, "/proto.v1.merchant.MerchantService/UpdateVerifiedMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchantDetailsByEmail(ctx context.Context, in *GetMerchantDetailsByEmailRequest, opts ...grpc.CallOption) (*GetMerchantDetailsByEmailResponse, error) {
	out := new(GetMerchantDetailsByEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.v1.merchant.MerchantService/GetMerchantDetailsByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
// All implementations must embed UnimplementedMerchantServiceServer
// for forward compatibility
type MerchantServiceServer interface {
	CreateMerchant(context.Context, *MerchantRequest) (*MerchantResponse, error)
	UpdateVerifiedMerchant(context.Context, *UpdateVerifiedMerchantRequest) (*UpdateVerifiedMerchantResponse, error)
	GetMerchantDetailsByEmail(context.Context, *GetMerchantDetailsByEmailRequest) (*GetMerchantDetailsByEmailResponse, error)
	mustEmbedUnimplementedMerchantServiceServer()
}

// UnimplementedMerchantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMerchantServiceServer struct {
}

func (UnimplementedMerchantServiceServer) CreateMerchant(context.Context, *MerchantRequest) (*MerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) UpdateVerifiedMerchant(context.Context, *UpdateVerifiedMerchantRequest) (*UpdateVerifiedMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVerifiedMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) GetMerchantDetailsByEmail(context.Context, *GetMerchantDetailsByEmailRequest) (*GetMerchantDetailsByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantDetailsByEmail not implemented")
}
func (UnimplementedMerchantServiceServer) mustEmbedUnimplementedMerchantServiceServer() {}

// UnsafeMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantServiceServer will
// result in compilation errors.
type UnsafeMerchantServiceServer interface {
	mustEmbedUnimplementedMerchantServiceServer()
}

func RegisterMerchantServiceServer(s grpc.ServiceRegistrar, srv MerchantServiceServer) {
	s.RegisterService(&MerchantService_ServiceDesc, srv)
}

func _MerchantService_CreateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).CreateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.merchant.MerchantService/CreateMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).CreateMerchant(ctx, req.(*MerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_UpdateVerifiedMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVerifiedMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).UpdateVerifiedMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.merchant.MerchantService/UpdateVerifiedMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).UpdateVerifiedMerchant(ctx, req.(*UpdateVerifiedMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchantDetailsByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantDetailsByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchantDetailsByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.merchant.MerchantService/GetMerchantDetailsByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchantDetailsByEmail(ctx, req.(*GetMerchantDetailsByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantService_ServiceDesc is the grpc.ServiceDesc for MerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.merchant.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMerchant",
			Handler:    _MerchantService_CreateMerchant_Handler,
		},
		{
			MethodName: "UpdateVerifiedMerchant",
			Handler:    _MerchantService_UpdateVerifiedMerchant_Handler,
		},
		{
			MethodName: "GetMerchantDetailsByEmail",
			Handler:    _MerchantService_GetMerchantDetailsByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/merchant/merchant.proto",
}
